<?php

return array (
  'LK-11' => __('Colombo', 'woocommerce-enhanced-regions'),
  'LK-12' => __('Gampaha', 'woocommerce-enhanced-regions'),
  'LK-13' => __('Kalutara', 'woocommerce-enhanced-regions'),
  'LK-21' => __('Kandy', 'woocommerce-enhanced-regions'),
  'LK-22' => __('Matale', 'woocommerce-enhanced-regions'),
  'LK-23' => __('Nuwara Eliya', 'woocommerce-enhanced-regions'),
  'LK-31' => __('Galle', 'woocommerce-enhanced-regions'),
  'LK-32' => __('Matara', 'woocommerce-enhanced-regions'),
  'LK-33' => __('Hambantota', 'woocommerce-enhanced-regions'),
  'LK-41' => __('Jaffna', 'woocommerce-enhanced-regions'),
  'LK-42' => __('Kilinochchi', 'woocommerce-enhanced-regions'),
  'LK-43' => __('Mannar', 'woocommerce-enhanced-regions'),
  'LK-44' => __('Vavuniya', 'woocommerce-enhanced-regions'),
  'LK-45' => __('Mullaitivu', 'woocommerce-enhanced-regions'),
  'LK-51' => __('Batticaloa', 'woocommerce-enhanced-regions'),
  'LK-52' => __('Ampara', 'woocommerce-enhanced-regions'),
  'LK-53' => __('Trincomalee', 'woocommerce-enhanced-regions'),
  'LK-61' => __('Kurunegala', 'woocommerce-enhanced-regions'),
  'LK-62' => __('Puttalam', 'woocommerce-enhanced-regions'),
  'LK-71' => __('Anuradhapura', 'woocommerce-enhanced-regions'),
  'LK-72' => __('Polonnaruwa', 'woocommerce-enhanced-regions'),
  'LK-81' => __('Badulla', 'woocommerce-enhanced-regions'),
  'LK-82' => __('Monaragala', 'woocommerce-enhanced-regions'),
  'LK-91' => __('Ratnapura', 'woocommerce-enhanced-regions'),
  'LK-92' => __('Kegalle', 'woocommerce-enhanced-regions'),
);
