<?php

return array (
  'MH-ALK' => __('Ailuk', 'woocommerce-enhanced-regions'),
  'MH-ALL' => __('Ailinglaplap', 'woocommerce-enhanced-regions'),
  'MH-ARN' => __('Arno', 'woocommerce-enhanced-regions'),
  'MH-AUR' => __('Aur', 'woocommerce-enhanced-regions'),
  'MH-EBN' => __('Ebon', 'woocommerce-enhanced-regions'),
  'MH-ENE' => __('Enewetak', 'woocommerce-enhanced-regions'),
  'MH-JAL' => __('Jaluit', 'woocommerce-enhanced-regions'),
  'MH-KIL' => __('Kili', 'woocommerce-enhanced-regions'),
  'MH-KWA' => __('Kwajalein', 'woocommerce-enhanced-regions'),
  'MH-LAE' => __('Lae', 'woocommerce-enhanced-regions'),
  'MH-LIB' => __('Lib', 'woocommerce-enhanced-regions'),
  'MH-LIK' => __('Likiep', 'woocommerce-enhanced-regions'),
  'MH-MAJ' => __('Majuro', 'woocommerce-enhanced-regions'),
  'MH-MAL' => __('Maloelap', 'woocommerce-enhanced-regions'),
  'MH-MEJ' => __('Mejit', 'woocommerce-enhanced-regions'),
  'MH-MIL' => __('Mili', 'woocommerce-enhanced-regions'),
  'MH-NAM' => __('Namorik', 'woocommerce-enhanced-regions'),
  'MH-NMU' => __('Namu', 'woocommerce-enhanced-regions'),
  'MH-RON' => __('Rongelap', 'woocommerce-enhanced-regions'),
  'MH-UJA' => __('Ujae', 'woocommerce-enhanced-regions'),
  'MH-UTI' => __('Utirik', 'woocommerce-enhanced-regions'),
  'MH-WTH' => __('Wotho', 'woocommerce-enhanced-regions'),
  'MH-WTJ' => __('Wotje', 'woocommerce-enhanced-regions'),
);
