<?php

return array (
  'MW-LI' => __('Lilongwe', 'woocommerce-enhanced-regions'),
  'MW-BA' => __('Balaka', 'woocommerce-enhanced-regions'),
  'MW-BL' => __('Blantyre', 'woocommerce-enhanced-regions'),
  'MW-CK' => __('Chikwawa', 'woocommerce-enhanced-regions'),
  'MW-CR' => __('Chiradzulu', 'woocommerce-enhanced-regions'),
  'MW-CT' => __('Chitipa', 'woocommerce-enhanced-regions'),
  'MW-DE' => __('Dedza', 'woocommerce-enhanced-regions'),
  'MW-DO' => __('Dowa', 'woocommerce-enhanced-regions'),
  'MW-KA' => __('Karonga', 'woocommerce-enhanced-regions'),
  'MW-KS' => __('Kasungu', 'woocommerce-enhanced-regions'),
  'MW-LK' => __('Likoma', 'woocommerce-enhanced-regions'),
  'MW-MC' => __('Mchinji', 'woocommerce-enhanced-regions'),
  'MW-MG' => __('Mangochi', 'woocommerce-enhanced-regions'),
  'MW-MH' => __('Machinga', 'woocommerce-enhanced-regions'),
  'MW-MU' => __('Mulanje', 'woocommerce-enhanced-regions'),
  'MW-MW' => __('Mwanza', 'woocommerce-enhanced-regions'),
  'MW-MZ' => __('Mzimba', 'woocommerce-enhanced-regions'),
  'MW-NE' => __('Neno', 'woocommerce-enhanced-regions'),
  'MW-NB' => __('Nkhata Bay', 'woocommerce-enhanced-regions'),
  'MW-NK' => __('Nkhotakota', 'woocommerce-enhanced-regions'),
  'MW-NS' => __('Nsanje', 'woocommerce-enhanced-regions'),
  'MW-NU' => __('Ntcheu', 'woocommerce-enhanced-regions'),
  'MW-NI' => __('Ntchisi', 'woocommerce-enhanced-regions'),
  'MW-PH' => __('Phalombe', 'woocommerce-enhanced-regions'),
  'MW-RU' => __('Rumphi', 'woocommerce-enhanced-regions'),
  'MW-SA' => __('Salima', 'woocommerce-enhanced-regions'),
  'MW-TH' => __('Thyolo', 'woocommerce-enhanced-regions'),
  'MW-ZO' => __('Zomba', 'woocommerce-enhanced-regions'),
);
