<?php

return array (
  'SC-01' => __('Anse aux Pins', 'woocommerce-enhanced-regions'),
  'SC-02' => __('Anse Boileau', 'woocommerce-enhanced-regions'),
  'SC-03' => __('Anse Etoile', 'woocommerce-enhanced-regions'),
  'SC-04' => __('Au Cap', 'woocommerce-enhanced-regions'),
  'SC-05' => __('Anse Royale', 'woocommerce-enhanced-regions'),
  'SC-06' => __('Baie Lazare', 'woocommerce-enhanced-regions'),
  'SC-07' => __('Baie Sainte Anne', 'woocommerce-enhanced-regions'),
  'SC-08' => __('Beau Vallon', 'woocommerce-enhanced-regions'),
  'SC-09' => __('Bel Air', 'woocommerce-enhanced-regions'),
  'SC-10' => __('Bel Ombre', 'woocommerce-enhanced-regions'),
  'SC-11' => __('Cascade', 'woocommerce-enhanced-regions'),
  'SC-12' => __('Glacis', 'woocommerce-enhanced-regions'),
  'SC-13' => __('Grand\', 'woocommerce-enhanced-regions')Anse (Mahé)',
  'SC-14' => __('Grand\', 'woocommerce-enhanced-regions')Anse (Praslin)',
  'SC-15' => __('La Digue', 'woocommerce-enhanced-regions'),
  'SC-16' => __('La Rivière Anglaise', 'woocommerce-enhanced-regions'),
  'SC-17' => __('Mont Buxton', 'woocommerce-enhanced-regions'),
  'SC-18' => __('Mont Fleuri', 'woocommerce-enhanced-regions'),
  'SC-19' => __('Plaisance', 'woocommerce-enhanced-regions'),
  'SC-20' => __('Pointe La Rue', 'woocommerce-enhanced-regions'),
  'SC-21' => __('Port Glaud', 'woocommerce-enhanced-regions'),
  'SC-22' => __('Saint Louis', 'woocommerce-enhanced-regions'),
  'SC-23' => __('Takamaka', 'woocommerce-enhanced-regions'),
  'SC-24' => __('Les Mamelles', 'woocommerce-enhanced-regions'),
  'SC-25' => __('Roche Caiman', 'woocommerce-enhanced-regions'),
);
