<?php

return array (
  'TD-NDJ' => __('N\', 'woocommerce-enhanced-regions')Djamena',
  'TD-BA' => __('Batha', 'woocommerce-enhanced-regions'),
  'TD-LC' => __('Lac', 'woocommerce-enhanced-regions'),
  'TD-BG' => __('Bahr el Gazel', 'woocommerce-enhanced-regions'),
  'TD-BO' => __('Borkou', 'woocommerce-enhanced-regions'),
  'TD-EN' => __('Ennedi-Est', 'woocommerce-enhanced-regions'),
  'TD-EO' => __('Ennedi-Ouest', 'woocommerce-enhanced-regions'),
  'TD-GU' => __('Guéra', 'woocommerce-enhanced-regions'),
  'TD-HA' => __('Hadjer-Lamis', 'woocommerce-enhanced-regions'),
  'TD-KA' => __('Kanem', 'woocommerce-enhanced-regions'),
  'TD-LO' => __('Logone Occidental', 'woocommerce-enhanced-regions'),
  'TD-LR' => __('Logone Oriental', 'woocommerce-enhanced-regions'),
  'TD-MA' => __('Mandoul', 'woocommerce-enhanced-regions'),
  'TD-ME' => __('Mayo-Kebbi Est', 'woocommerce-enhanced-regions'),
  'TD-MO' => __('Mayo-Kebbi Ouest', 'woocommerce-enhanced-regions'),
  'TD-MC' => __('Moyen-Chari', 'woocommerce-enhanced-regions'),
  'TD-OD' => __('Ouaddaï', 'woocommerce-enhanced-regions'),
  'TD-SA' => __('Salamat', 'woocommerce-enhanced-regions'),
  'TD-SI' => __('Sila', 'woocommerce-enhanced-regions'),
  'TD-TA' => __('Tandjilé', 'woocommerce-enhanced-regions'),
  'TD-TI' => __('Tibesti', 'woocommerce-enhanced-regions'),
  'TD-WF' => __('Wadi Fira', 'woocommerce-enhanced-regions'),
  'TD-SD' => __('Salamat', 'woocommerce-enhanced-regions'),
);
