<?php

return array (
  'TW-TPE' => __('Taipei City', 'woocommerce-enhanced-regions'),
  'TW-KHH' => __('Kaohsiung City', 'woocommerce-enhanced-regions'),
  'TW-NWT' => __('New Taipei City', 'woocommerce-enhanced-regions'),
  'TW-TXG' => __('Taichung City', 'woocommerce-enhanced-regions'),
  'TW-TNN' => __('Tainan City', 'woocommerce-enhanced-regions'),
  'TW-TAO' => __('Taoyuan City', 'woocommerce-enhanced-regions'),
  'TW-ILA' => __('Yilan County', 'woocommerce-enhanced-regions'),
  'TW-HUA' => __('Hualien County', 'woocommerce-enhanced-regions'),
  'TW-KIN' => __('Kinmen County', 'woocommerce-enhanced-regions'),
  'TW-NAN' => __('Nantou County', 'woocommerce-enhanced-regions'),
  'TW-PEN' => __('Penghu County', 'woocommerce-enhanced-regions'),
  'TW-PIF' => __('Pingtung County', 'woocommerce-enhanced-regions'),
  'TW-TTT' => __('Taitung County', 'woocommerce-enhanced-regions'),
  'TW-MIA' => __('Miaoli County', 'woocommerce-enhanced-regions'),
  'TW-HSQ' => __('Hsinchu County', 'woocommerce-enhanced-regions'),
  'TW-CYQ' => __('Chiayi County', 'woocommerce-enhanced-regions'),
  'TW-YUN' => __('Yunlin County', 'woocommerce-enhanced-regions'),
  'TW-CHA' => __('Changhua County', 'woocommerce-enhanced-regions'),
  'TW-KEE' => __('Keelung City', 'woocommerce-enhanced-regions'),
  'TW-HSZ' => __('Hsinchu City', 'woocommerce-enhanced-regions'),
  'TW-CYI' => __('Chiayi City', 'woocommerce-enhanced-regions'),
);
